version: '2'

services:
  yknmariadb:
    restart: always
    image: mariadb:latest
    ports:
      - "27118:3306"
    volumes:
      - ykn-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yokinu
      - MYSQL_USER=ykn
      - MYSQL_PASSWORD=ykn
  yknserver:
    restart: always
    build: .
    image: ykn/server:dev
    ports:
      - 4100:4100
    links:
      - yknmariadb:mariadb
      - yknelasticsearch:elasticsearch
    volumes:
      - .:/usr/src/ykn
      - ykn-server-logs:/var/log/yokinu
    environment:
      - NODE_ENV=development
  yknelasticsearch:
    restart: always
    image: elasticsearch:alpine
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - ykn-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - node.master=true
      - transport.host=127.0.0.1
volumes:
  ykn-mariadb-data:
    driver: local
  ykn-elasticsearch-data:
    driver: local
  ykn-server-logs:
    driver: local
