version: '2'

services:
  yknmongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27118:27017"
    volumes:
      - ykn-mongodb-data:/data/db
  yknserver:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ykn/server:prod
    ports:
      - 4101:4100
    links:
      - yknmongodb:mongodb
volumes:
  ykn-mongodb-data:
    driver: local