version: '3'

services:
  yknmariadb:
    restart: always
    image: mariadb:10.3
    ports:
      - "27118:3306"
    volumes:
      - ykn-mariadb-data:/var/lib/mysql
    networks:
      default:
       aliases:
         - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yokinu
      - MYSQL_USER=ykn
      - MYSQL_PASSWORD=ykn
  yknserver:
    restart: always
    build: .
    image: ykn/server:dev
    ports:
      - "4100:4100"
    networks:
      default:
       aliases:
         - yknserver
    depends_on:
      - yknmariadb
      - yknelasticsearch
      - yknredis
    volumes:
      - ./scripts:/usr/src/ykn/scripts
      - ./config:/usr/src/ykn/config
      - ./src:/usr/src/ykn/src
      - ykn-server-data:/data
      - ykn-server-logs:/var/log/yokinu
    environment:
      - NODE_ENV=development
  yknelasticsearch:
    restart: always
    image: elasticsearch:6.4.2
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - ykn-elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - elasticsearch
    environment:
      - http.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - node.master=true
      - transport.host=127.0.0.1
  yknredis:
    restart: always
    image: redis:alpine
    ports:
      - "6479:6379"
    volumes:
      - ykn-redis-data:/data
    networks:
      default:
        aliases:
          - redis

volumes:
  ykn-mariadb-data:
    driver: local
  ykn-elasticsearch-data:
    driver: local
  ykn-redis-data:
    driver: local
  ykn-server-data:
    driver: local
  ykn-server-logs:
    driver: local
